name: Build and Deploy React App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Archive production-ready files
      run: zip -r build.zip build

    - name: Deploy to Azure Web App
      env:
        AZURE_PUBLISH_URL: ${{ secrets.AZURE_PUBLISH_URL }}
        AZURE_USER_NAME: ${{ secrets.AZURE_USER_NAME }}
        AZURE_USER_PWD: ${{ secrets.AZURE_USER_PWD }}
      run: |
        curl -X POST -u $AZURE_USER_NAME:$AZURE_USER_PWD \
          --data-binary @"build.zip" \
          https://$AZURE_PUBLISH_URL/api/zipdeploy
